import { createContext, useContext, useState, useEffect } from "react";

const translations = {
  pt: {
    languageCode: "PT-BR",
    languageLabel: "Trocar idioma",
    // Home
    nickPlaceholder: "Digite seu nick...",
    play: "JOGAR",
    enterCode: "Entrar com código",
    enterCodeTitle: "Insira o código da partida",
    codePlaceholder: "Ex: ABC-123",
    cancel: "Cancelar",
    enter: "Entrar",
    howItWorks: "COMO FUNCIONA",
    secretCode: "O mestre dá uma dica: uma palavra e um número para guiar os agentes",
    solveChallenges: "Os agentes votam nas cartas — 3 votos revelam uma carta do tabuleiro",
    fastestWins: "Cuidado: um impostor secreto tenta fazer os agentes virarem a carta errada",
    chooseAvatar: "Escolha seu Avatar",
    close: "Fechar",
    avatarAlt: "Avatar",
    defaultNick: "Jogador",
    // Lobby
    master: "MESTRE",
    agents: "AGENTES",
    rules: "Regras",
    settings: "Configurações",
    help: "Ajuda",
    kickBtn: "× Expulsar",
    moveToAgents: "↓ Agentes",
    moveToMaster: "↑",
    masterClueDesc: "As dicas estão em suas mãos.",
    noMaster: "Nenhum mestre ainda.",
    leave: "✕ Sair",
    occupied: "Ocupado",
    joinRole: "Entrar",
    players: "JOGADORES",
    inviteDescLine1: "Convide seus amigos para entrar na partida.",
    inviteDescLine2: "Quanto mais agentes, mais desafiador!",
    inTeam: "NA EQUIPE",
    noAgents: "Nenhum agente ainda",
    randomizeAgents: "Randomizar Agentes",
    resetAgents: "Redefinir Agentes",
    timePerRound: "Tempo por rodada",
    secondsPlaceholder: "Segundos...",
    changeTimer: "Alterar",
    setTimer: "Definir",
    timerActive: (s) => `⏱ ${s}s por rodada definido`,
    timerInfo: (s) => `⏱ ${s}s por rodada`,
    startGame: "INICIAR JOGO",
    kicked: "Você foi removido da sala",
    // Game
    loading: "Carregando...",
    giveClueMaster: { pre: "DÊ UMA ", hl1: "DICA", mid: " PARA SEUS ", hl2: "AGENTES" },
    youAreImpostor: { pre: "VOCÊ É O ", hl1: "IMPOSTOR", mid: ", ATRAPALHE OS ", hl2: "AGENTES" },
    youAreAgent: { pre: "VOCÊ É UM ", hl1: "AGENTE", mid: ", ESPERE A DICA DO ", hl2: "MESTRE" },
    masterLabel: "MESTRE",
    agentsLabel: "AGENTES",
    exitGame: "SAIR",
    roundLog: "REGISTRO DAS RODADAS",
    returnToLobby: "VOLTAR TODOS AO LOBBY",
    cluePlaceholder: "Sua dica (uma palavra)...",
    remaining: "Restam",
    gameOver: "PARTIDA ENCERRADA",
    impostorWon: "O IMPOSTOR VENCEU!",
    agentsWon: "OS AGENTES VENCERAM!",
  },
  en: {
    languageCode: "EN-US",
    languageLabel: "Change language",
    // Home
    nickPlaceholder: "Enter your nickname...",
    play: "PLAY",
    enterCode: "Enter with code",
    enterCodeTitle: "Enter the game code",
    codePlaceholder: "Ex: ABC-123",
    cancel: "Cancel",
    enter: "Enter",
    howItWorks: "HOW IT WORKS",
    secretCode: "The master gives a clue: one word and a number to guide the agents",
    solveChallenges: "Agents vote on cards — 3 votes flip a card on the board",
    fastestWins: "Watch out: a secret impostor tries to make agents flip the wrong card",
    chooseAvatar: "Choose your Avatar",
    close: "Close",
    avatarAlt: "Avatar",
    defaultNick: "Player",
    // Lobby
    master: "MASTER",
    agents: "AGENTS",
    rules: "Rules",
    settings: "Settings",
    help: "Help",
    kickBtn: "× Kick",
    moveToAgents: "↓ Agents",
    moveToMaster: "↑",
    masterClueDesc: "The clues are in their hands.",
    noMaster: "No master yet.",
    leave: "✕ Leave",
    occupied: "Occupied",
    joinRole: "Join",
    players: "PLAYERS",
    inviteDescLine1: "Invite your friends to join the game.",
    inviteDescLine2: "The more agents, the more challenging!",
    inTeam: "IN TEAM",
    noAgents: "No agents yet",
    randomizeAgents: "Randomize Agents",
    resetAgents: "Reset Agents",
    timePerRound: "Time per round",
    secondsPlaceholder: "Seconds...",
    changeTimer: "Change",
    setTimer: "Set",
    timerActive: (s) => `⏱ ${s}s per round set`,
    timerInfo: (s) => `⏱ ${s}s per round`,
    startGame: "START GAME",
    kicked: "You were removed from the room",
    // Game
    loading: "Loading...",
    giveClueMaster: { pre: "GIVE A ", hl1: "CLUE", mid: " TO YOUR ", hl2: "AGENTS" },
    youAreImpostor: { pre: "YOU ARE THE ", hl1: "IMPOSTOR", mid: ", DISRUPT THE ", hl2: "AGENTS" },
    youAreAgent: { pre: "YOU ARE AN ", hl1: "AGENT", mid: ", WAIT FOR THE ", hl2: "MASTER'S CLUE" },
    masterLabel: "MASTER",
    agentsLabel: "AGENTS",
    exitGame: "EXIT",
    roundLog: "ROUND LOG",
    returnToLobby: "RETURN ALL TO LOBBY",
    cluePlaceholder: "Your clue (one word)...",
    remaining: "Remaining",
    gameOver: "GAME OVER",
    impostorWon: "THE IMPOSTOR WON!",
    agentsWon: "THE AGENTS WON!",
  },
  es: {
    languageCode: "ES",
    languageLabel: "Cambiar idioma",
    // Home
    nickPlaceholder: "Escribe tu apodo...",
    play: "JUGAR",
    enterCode: "Entrar con código",
    enterCodeTitle: "Inserta el código de partida",
    codePlaceholder: "Ej: ABC-123",
    cancel: "Cancelar",
    enter: "Entrar",
    howItWorks: "COMO FUNCIONA",
    secretCode: "El maestro da una pista: una palabra y un número para guiar a los agentes",
    solveChallenges: "Los agentes votan en cartas — 3 votos revelan una carta del tablero",
    fastestWins: "Cuidado: un impostor secreto intenta que los agentes elijan la carta equivocada",
    chooseAvatar: "Elige tu Avatar",
    close: "Cerrar",
    avatarAlt: "Avatar",
    defaultNick: "Jugador",
    // Lobby
    master: "MAESTRO",
    agents: "AGENTES",
    rules: "Reglas",
    settings: "Configuración",
    help: "Ayuda",
    kickBtn: "× Expulsar",
    moveToAgents: "↓ Agentes",
    moveToMaster: "↑",
    masterClueDesc: "Las pistas están en sus manos.",
    noMaster: "Sin maestro aún.",
    leave: "✕ Salir",
    occupied: "Ocupado",
    joinRole: "Entrar",
    players: "JUGADORES",
    inviteDescLine1: "Invita a tus amigos a unirse a la partida.",
    inviteDescLine2: "¡Más agentes, más desafiante!",
    inTeam: "EN EQUIPO",
    noAgents: "Sin agentes aún",
    randomizeAgents: "Aleatorizar Agentes",
    resetAgents: "Reiniciar Agentes",
    timePerRound: "Tiempo por ronda",
    secondsPlaceholder: "Segundos...",
    changeTimer: "Cambiar",
    setTimer: "Definir",
    timerActive: (s) => `⏱ ${s}s por ronda definido`,
    timerInfo: (s) => `⏱ ${s}s por ronda`,
    startGame: "INICIAR JUEGO",
    kicked: "Fuiste removido de la sala",
    // Game
    loading: "Cargando...",
    giveClueMaster: { pre: "DA UNA ", hl1: "PISTA", mid: " A TUS ", hl2: "AGENTES" },
    youAreImpostor: { pre: "ERES EL ", hl1: "IMPOSTOR", mid: ", OBSTACULIZA A LOS ", hl2: "AGENTES" },
    youAreAgent: { pre: "ERES UN ", hl1: "AGENTE", mid: ", ESPERA LA PISTA DEL ", hl2: "MAESTRO" },
    masterLabel: "MAESTRO",
    agentsLabel: "AGENTES",
    exitGame: "SALIR",
    roundLog: "REGISTRO DE RONDAS",
    returnToLobby: "VOLVER TODOS AL LOBBY",
    cluePlaceholder: "Tu pista (una palabra)...",
    remaining: "Quedan",
    gameOver: "PARTIDA TERMINADA",
    impostorWon: "¡EL IMPOSTOR GANÓ!",
    agentsWon: "¡LOS AGENTES GANARON!",
  },
  fr: {
    languageCode: "FR",
    languageLabel: "Changer de langue",
    // Home
    nickPlaceholder: "Entrez votre pseudo...",
    play: "JOUER",
    enterCode: "Entrer avec code",
    enterCodeTitle: "Entrez le code de partie",
    codePlaceholder: "Ex: ABC-123",
    cancel: "Annuler",
    enter: "Entrer",
    howItWorks: "COMMENT ÇA MARCHE",
    secretCode: "Le maître donne un indice : un mot et un chiffre pour guider les agents",
    solveChallenges: "Les agents votent sur les cartes — 3 votes révèlent une carte du plateau",
    fastestWins: "Attention : un imposteur secret tente de faire choisir la mauvaise carte",
    chooseAvatar: "Choisissez votre Avatar",
    close: "Fermer",
    avatarAlt: "Avatar",
    defaultNick: "Joueur",
    // Lobby
    master: "MAÎTRE",
    agents: "AGENTS",
    rules: "Règles",
    settings: "Paramètres",
    help: "Aide",
    kickBtn: "× Expulser",
    moveToAgents: "↓ Agents",
    moveToMaster: "↑",
    masterClueDesc: "Les indices sont entre ses mains.",
    noMaster: "Pas encore de maître.",
    leave: "✕ Quitter",
    occupied: "Occupé",
    joinRole: "Rejoindre",
    players: "JOUEURS",
    inviteDescLine1: "Invitez vos amis à rejoindre la partie.",
    inviteDescLine2: "Plus il y a d'agents, plus c'est difficile !",
    inTeam: "EN ÉQUIPE",
    noAgents: "Pas encore d'agents",
    randomizeAgents: "Mélanger les Agents",
    resetAgents: "Réinitialiser les Agents",
    timePerRound: "Temps par tour",
    secondsPlaceholder: "Secondes...",
    changeTimer: "Modifier",
    setTimer: "Définir",
    timerActive: (s) => `⏱ ${s}s par tour défini`,
    timerInfo: (s) => `⏱ ${s}s par tour`,
    startGame: "DÉMARRER LE JEU",
    kicked: "Vous avez été retiré de la salle",
    // Game
    loading: "Chargement...",
    giveClueMaster: { pre: "DONNEZ UN ", hl1: "INDICE", mid: " À VOS ", hl2: "AGENTS" },
    youAreImpostor: { pre: "VOUS ÊTES L'", hl1: "IMPOSTEUR", mid: ", GÊNEZ LES ", hl2: "AGENTS" },
    youAreAgent: { pre: "VOUS ÊTES UN ", hl1: "AGENT", mid: ", ATTENDEZ L'INDICE DU ", hl2: "MAÎTRE" },
    masterLabel: "MAÎTRE",
    agentsLabel: "AGENTS",
    exitGame: "QUITTER",
    roundLog: "JOURNAL DES TOURS",
    returnToLobby: "RETOUR AU LOBBY",
    cluePlaceholder: "Votre indice (un mot)...",
    remaining: "Restant",
    gameOver: "PARTIE TERMINÉE",
    impostorWon: "L'IMPOSTEUR A GAGNÉ !",
    agentsWon: "LES AGENTS ONT GAGNÉ !",
  },
  it: {
    languageCode: "IT",
    languageLabel: "Cambia lingua",
    // Home
    nickPlaceholder: "Inserisci il tuo nick...",
    play: "GIOCA",
    enterCode: "Entra con codice",
    enterCodeTitle: "Inserisci il codice partita",
    codePlaceholder: "Es: ABC-123",
    cancel: "Annulla",
    enter: "Entra",
    howItWorks: "COME FUNZIONA",
    secretCode: "Il maestro dà un indizio: una parola e un numero per guidare gli agenti",
    solveChallenges: "Gli agenti votano sulle carte — 3 voti rivelano una carta del tabellone",
    fastestWins: "Attenzione: un impostore segreto cerca di far scegliere la carta sbagliata",
    chooseAvatar: "Scegli il tuo Avatar",
    close: "Chiudi",
    avatarAlt: "Avatar",
    defaultNick: "Giocatore",
    // Lobby
    master: "MAESTRO",
    agents: "AGENTI",
    rules: "Regole",
    settings: "Impostazioni",
    help: "Aiuto",
    kickBtn: "× Espelli",
    moveToAgents: "↓ Agenti",
    moveToMaster: "↑",
    masterClueDesc: "Gli indizi sono nelle sue mani.",
    noMaster: "Nessun maestro ancora.",
    leave: "✕ Esci",
    occupied: "Occupato",
    joinRole: "Entra",
    players: "GIOCATORI",
    inviteDescLine1: "Invita i tuoi amici a unirsi alla partita.",
    inviteDescLine2: "Più agenti, più difficile!",
    inTeam: "IN SQUADRA",
    noAgents: "Nessun agente ancora",
    randomizeAgents: "Randomizza Agenti",
    resetAgents: "Reimposta Agenti",
    timePerRound: "Tempo per turno",
    secondsPlaceholder: "Secondi...",
    changeTimer: "Modifica",
    setTimer: "Imposta",
    timerActive: (s) => `⏱ ${s}s per turno impostato`,
    timerInfo: (s) => `⏱ ${s}s per turno`,
    startGame: "INIZIA IL GIOCO",
    kicked: "Sei stato rimosso dalla stanza",
    // Game
    loading: "Caricamento...",
    giveClueMaster: { pre: "DAI UN ", hl1: "INDIZIO", mid: " AI TUOI ", hl2: "AGENTI" },
    youAreImpostor: { pre: "SEI L'", hl1: "IMPOSTORE", mid: ", OSTACOLA GLI ", hl2: "AGENTI" },
    youAreAgent: { pre: "SEI UN ", hl1: "AGENTE", mid: ", ASPETTA L'INDIZIO DEL ", hl2: "MAESTRO" },
    masterLabel: "MAESTRO",
    agentsLabel: "AGENTI",
    exitGame: "ESCI",
    roundLog: "REGISTRO DEI TURNI",
    returnToLobby: "TUTTI AL LOBBY",
    cluePlaceholder: "Il tuo indizio (una parola)...",
    remaining: "Rimangono",
    gameOver: "PARTITA TERMINATA",
    impostorWon: "L'IMPOSTORE HA VINTO!",
    agentsWon: "GLI AGENTI HANNO VINTO!",
  },
  zh: {
    languageCode: "ZH",
    languageLabel: "切换语言",
    // Home
    nickPlaceholder: "输入你的昵称...",
    play: "开始",
    enterCode: "用代码进入",
    enterCodeTitle: "输入游戏代码",
    codePlaceholder: "例: ABC-123",
    cancel: "取消",
    enter: "进入",
    howItWorks: "玩法说明",
    secretCode: "主人给出提示：一个词和一个数字，引导特工找到正确的卡片",
    solveChallenges: "特工对卡片投票——3票即可翻开棋盘上的一张卡片",
    fastestWins: "小心：一名秘密内鬼试图让特工翻开错误的卡片",
    chooseAvatar: "选择你的头像",
    close: "关闭",
    avatarAlt: "头像",
    defaultNick: "玩家",
    // Lobby
    master: "主人",
    agents: "特工",
    rules: "规则",
    settings: "设置",
    help: "帮助",
    kickBtn: "× 踢出",
    moveToAgents: "↓ 特工",
    moveToMaster: "↑",
    masterClueDesc: "提示都在他们手中。",
    noMaster: "还没有主人。",
    leave: "✕ 离开",
    occupied: "已占用",
    joinRole: "加入",
    players: "玩家",
    inviteDescLine1: "邀请你的朋友加入游戏。",
    inviteDescLine2: "特工越多，挑战越大！",
    inTeam: "在队伍中",
    noAgents: "还没有特工",
    randomizeAgents: "随机排列特工",
    resetAgents: "重置特工",
    timePerRound: "每轮时间",
    secondsPlaceholder: "秒数...",
    changeTimer: "修改",
    setTimer: "设定",
    timerActive: (s) => `⏱ 每轮 ${s}秒 已设定`,
    timerInfo: (s) => `⏱ 每轮 ${s}秒`,
    startGame: "开始游戏",
    kicked: "你已被移出房间",
    // Game
    loading: "加载中...",
    giveClueMaster: { pre: "给你的", hl1: "特工", mid: "一个", hl2: "提示" },
    youAreImpostor: { pre: "你是", hl1: "内鬼", mid: "，阻止", hl2: "特工" },
    youAreAgent: { pre: "你是", hl1: "特工", mid: "，等待", hl2: "主人的提示" },
    masterLabel: "主人",
    agentsLabel: "特工",
    exitGame: "退出",
    roundLog: "回合记录",
    returnToLobby: "全员返回大厅",
    cluePlaceholder: "你的提示（一个词）...",
    remaining: "剩余",
    gameOver: "游戏结束",
    impostorWon: "内鬼获胜！",
    agentsWon: "特工获胜！",
  },
};

const languageOptions = ["pt", "en", "es", "fr", "it", "zh"];

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem("selectedLanguage");
    return saved && translations[saved] ? saved : "pt";
  });

  const toggleLanguage = () => {
    const next = languageOptions[(languageOptions.indexOf(language) + 1) % languageOptions.length];
    setLanguage(next);
    localStorage.setItem("selectedLanguage", next);
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
